[project]
name = "the-wrapping-book"
version = "0.1.0"
description = "Repository to create a book using content from thewrappinggallery.com"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-decouple>=3.8",
    "reportlab>=4.3.1",
    "supabase>=2.15.0",
]
